2017-05-20 01:15:53,515 ERROR [11] SendMailClass.Mailer - An invalid character was found in the mail header: ','.
2017-05-20 01:21:33,132 ERROR [10] SendMailClass.Mailer - An invalid character was found in the mail header: ','.
2017-05-20 20:35:14,760 ERROR [19] SendMailClass.Mailer - Failure sending mail.
2017-05-20 20:35:47,954 ERROR [20] SendMailClass.Mailer - Failure sending mail.
2017-05-20 20:43:41,431 ERROR [6] SendMailClass.Mailer - Failure sending mail.
