2017-05-25 22:59:19,190 ERROR [10] SendMailClass.Mailer - The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.5.1 Authentication Required. Learn more at
2017-05-25 23:13:25,971 ERROR [6] SendMailClass.Mailer - Failure sending mail.
2017-05-25 23:26:43,097 ERROR [6] SendMailClass.Mailer - The operation has timed out.
2017-05-25 23:28:49,788 ERROR [6] SendMailClass.Mailer - The operation has timed out.
2017-05-25 23:48:49,401 ERROR [6] SendMailClass.Mailer - Failure sending mail.
